name: musicvault

services:
  backend:
    image: ghcr.io/cpsc-491-group-2/musicvault-backend:${TAG:-latest}
    build: ./backend
    restart: unless-stopped
    ports:
      - "5000:5000"

  frontend:
    image: ghcr.io/cpsc-491-group-2/musicvault-frontend:${TAG:-latest}
    build: ./frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "3000:3000"
