-- ============================================================
-- MUSICVAULT INITIAL DATABASE SCHEMA
-- PostgreSQL / Supabase
-- ============================================================


-- ============================================================
-- 1. EXTENSIONS
-- ============================================================

CREATE EXTENSION IF NOT EXISTS "pgcrypto";


-- ============================================================
-- 2. USERS
-- Core MusicVault user accounts.
-- Email is nullable because Spotify no longer guarantees email.
-- ============================================================

CREATE TABLE users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    email VARCHAR(320) UNIQUE,
    display_name VARCHAR(255),

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


-- ============================================================
-- 3. LINKED SPOTIFY ACCOUNTS
-- Stores the user's linked Spotify identity and OAuth metadata.
-- spotify_account_id should be treated as the stable external
-- account-linking identifier.
-- ============================================================

CREATE TABLE spotify_accounts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    user_id UUID NOT NULL UNIQUE
        REFERENCES users(id)
        ON DELETE CASCADE,

    spotify_account_id VARCHAR(255) NOT NULL UNIQUE,

    spotify_user_id VARCHAR(255),
    display_name VARCHAR(255),

    access_token TEXT,
    refresh_token TEXT,
    token_expires_at TIMESTAMPTZ,
    scope TEXT,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


-- ============================================================
-- 4. SONGS
-- Canonical MusicVault song records.
-- Spotify metadata is optional; Spotify is not assumed to be
-- the authoritative source for all song data.
-- ============================================================

CREATE TABLE songs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    title VARCHAR(500) NOT NULL,
    artist_name VARCHAR(500) NOT NULL,
    album_name VARCHAR(500),

    spotify_track_id VARCHAR(255) UNIQUE,

    duration_ms INTEGER,
    explicit BOOLEAN,

    popularity INTEGER,
    popularity_source VARCHAR(100),

    audio_features JSONB,
    audio_features_source VARCHAR(100),

    spotify_url TEXT,
    album_image_url TEXT,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_song_duration_nonnegative
        CHECK (duration_ms IS NULL OR duration_ms >= 0),

    CONSTRAINT chk_song_popularity_range
        CHECK (
            popularity IS NULL
            OR popularity BETWEEN 0 AND 100
        )
);


-- ============================================================
-- 5. USER SONG PREFERENCES
-- Stores user sentiment / interaction with songs.
-- Allows MusicVault to build recommendation signals internally.
-- ============================================================

CREATE TABLE user_preferences (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    user_id UUID NOT NULL
        REFERENCES users(id)
        ON DELETE CASCADE,

    song_id UUID NOT NULL
        REFERENCES songs(id)
        ON DELETE CASCADE,

    preference_type VARCHAR(50) NOT NULL,
    rating SMALLINT,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_user_preferences_user_song
        UNIQUE (user_id, song_id),

    CONSTRAINT chk_user_preferences_rating
        CHECK (
            rating IS NULL
            OR rating BETWEEN 1 AND 5
        ),

    CONSTRAINT chk_user_preferences_type
        CHECK (
            preference_type IN (
                'liked',
                'disliked',
                'saved',
                'skipped',
                'neutral'
            )
        )
);


-- ============================================================
-- 6. RECOMMENDATIONS
-- Stores recommendations generated by MusicVault.
-- Does NOT assume Spotify's removed Recommendations endpoint.
-- ============================================================

CREATE TABLE recommendations (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    user_id UUID NOT NULL
        REFERENCES users(id)
        ON DELETE CASCADE,

    song_id UUID NOT NULL
        REFERENCES songs(id)
        ON DELETE CASCADE,

    score DOUBLE PRECISION,
    reason TEXT,
    algorithm_version VARCHAR(100),

    generated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_recommendations_user_song
        UNIQUE (user_id, song_id),

    CONSTRAINT chk_recommendation_score
        CHECK (
            score IS NULL
            OR score >= 0
        )
);


-- ============================================================
-- 7. CHARTS
-- Represents external or internally generated charts.
-- The chart source is provider-neutral and should not assume
-- Spotify is the source.
-- ============================================================

CREATE TABLE charts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    name VARCHAR(255) NOT NULL,
    source VARCHAR(100) NOT NULL,
    chart_date DATE NOT NULL,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_charts_name_source_date
        UNIQUE (name, source, chart_date)
);


-- ============================================================
-- 8. CHART ENTRIES
-- Connects songs to charts and stores their ranking position.
-- ============================================================

CREATE TABLE chart_entries (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    chart_id UUID NOT NULL
        REFERENCES charts(id)
        ON DELETE CASCADE,

    song_id UUID NOT NULL
        REFERENCES songs(id)
        ON DELETE CASCADE,

    position INTEGER NOT NULL,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_chart_entries_chart_position
        UNIQUE (chart_id, position),

    CONSTRAINT uq_chart_entries_chart_song
        UNIQUE (chart_id, song_id),

    CONSTRAINT chk_chart_position_positive
        CHECK (position > 0)
);


-- ============================================================
-- 9. INDEXES
-- Additional indexes for common lookup and join patterns.
-- ============================================================

CREATE INDEX idx_users_email
    ON users(email);


CREATE INDEX idx_spotify_accounts_user_id
    ON spotify_accounts(user_id);


CREATE INDEX idx_spotify_accounts_spotify_account_id
    ON spotify_accounts(spotify_account_id);


CREATE INDEX idx_songs_spotify_track_id
    ON songs(spotify_track_id);


CREATE INDEX idx_songs_title
    ON songs(title);


CREATE INDEX idx_songs_artist_name
    ON songs(artist_name);


CREATE INDEX idx_user_preferences_user_id
    ON user_preferences(user_id);


CREATE INDEX idx_user_preferences_song_id
    ON user_preferences(song_id);


CREATE INDEX idx_user_preferences_type
    ON user_preferences(preference_type);


CREATE INDEX idx_recommendations_user_id
    ON recommendations(user_id);


CREATE INDEX idx_recommendations_song_id
    ON recommendations(song_id);


CREATE INDEX idx_recommendations_user_score
    ON recommendations(user_id, score DESC);


CREATE INDEX idx_charts_date
    ON charts(chart_date);


CREATE INDEX idx_charts_source
    ON charts(source);


CREATE INDEX idx_chart_entries_chart_id
    ON chart_entries(chart_id);


CREATE INDEX idx_chart_entries_song_id
    ON chart_entries(song_id);


CREATE INDEX idx_chart_entries_chart_position
    ON chart_entries(chart_id, position);


-- ============================================================
-- 10. SCHEMA RELATIONSHIP SUMMARY
-- ============================================================

/*
    users
      |
      | 1 : 0..1
      v
    spotify_accounts


    users
      |
      | 1 : many
      v
    user_preferences
      |
      | many : 1
      v
    songs


    users
      |
      | 1 : many
      v
    recommendations
      |
      | many : 1
      v
    songs


    charts
      |
      | 1 : many
      v
    chart_entries
      |
      | many : 1
      v
    songs
*/


-- ============================================================
-- 11. IMPORTANT DESIGN NOTES
-- ============================================================

/*
1. users.email is nullable.
   Spotify-only registration must not depend on email.

2. spotify_accounts is optional.
   A MusicVault user can exist without linking Spotify.

3. songs.spotify_track_id is nullable.
   Songs may originate from non-Spotify chart or metadata sources.

4. popularity is provider-neutral.
   Spotify does not reliably provide track popularity for current
   Development Mode applications.

5. audio_features is provider-neutral.
   Spotify Audio Features is not assumed to be available.

6. charts are source-neutral.
   MusicVault's Top 100 feature must not depend on Spotify-owned
   editorial/chart playlists.

7. recommendations are generated and owned by MusicVault.
   They do not represent Spotify's removed Recommendations API.

8. OAuth credentials must never be committed to Git.
   Production token storage may later be encrypted or moved into
   a dedicated secure credential mechanism.
*/